config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  root 'home#index'
  resources :listings
  get '/connect', to: 'registration#connect', as: 'smart'
  get '/oauth/callback', to: 'registration#callback'
  get '/getswitch', to: 'registration#switch'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  DEVICE_OPTIONS = ['Light Switch', 'Lock', 'Thermostat']
  validates_inclusion_of :name, :in => DEVICE_OPTIONS
  belongs_to :listing

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :devices
  has_one :reservation, dependent: :destroy
  validates_presence_of :reservation
  accepts_nested_attributes_for :reservation
  accepts_nested_attributes_for :devices, reject_if: :all_blank, allow_destroy: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :listing
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # def current_resource_owner
  #   User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  # end

  # def current_user
  #   current_resource_owner
  # end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @listing.devices.build
    @listing.build_reservation
  end

  # GET /listings/1/edit
  def edit
    @listing.build_reservation if @product.reservation.nil?
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(
        :user_id,
        :automation,
        reservation_attributes: [ :id, :start_date, :end_date ],
        devices_attributes: [ :id, :name,:_destroy ]
      )
    end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  before_action :set_client

  def connect
    url = @client.auth_code.authorize_url(redirect_uri: @redirect_uri, scope: 'app')
    redirect_to url
  end

  def callback
    code = params[:code]
    response = @client.auth_code.get_token(code, redirect_uri: @redirect_uri, scope: 'app')
    session[:access_token] = response.token
    current_user.auth_token = response.token
    current_user.save
    redirect_to getswitch_url
  end

  def switch
    if !authenticated?
      redirect_to root_path
      return
    end
    token = session[:access_token]
    url = URI.parse(@endpoints_uri)
    req = Net::HTTP::Get.new(url.request_uri)
    req['Authorization'] = 'Bearer ' + token
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = (url.scheme == "https")
    response = http.request(req)
    json = JSON.parse(response.body)
    uri = json[0]['uri']
    switchUrl = uri + '/switches'
    getSwitchURL = URI.parse(switchUrl)
    getSwitchReq = Net::HTTP::Get.new(getSwitchURL.request_uri)
    getSwitchReq['Authorization'] = 'Bearer ' + token
    getSwitchHttp = Net::HTTP.new(getSwitchURL.host, getSwitchURL.port)
    getSwitchHttp.use_ssl = true
    switchStatus = getSwitchHttp.request(getSwitchReq)
    @response = JSON.parse(switchStatus.body)
  end

  def authenticated?
    session[:access_token]
  end

  private

  def set_client
    options = {
      site: 'https://graph.api.smartthings.com',
      authorize_url: '/oauth/authorize',
      token_url: '/oauth/token'
    }
    @redirect_uri = 'https://dewswitch.herokuapp.com/oauth/callback'
    @endpoints_uri = 'https://graph.api.smartthings.com/api/smartapps/endpoints'
    @client = OAuth2::Client.new(ENV['CLIENT_ID'], ENV['CLIENT_SECRET'], options)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/application/_header.html.erb
<nav id="navbar-example2" class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Switch</a>
  <ul class="nav nav-pills">
    <li class="nav-item">
      <%= link_to 'Home', root_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'SmartThings', getswitch_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Create Listing', new_listing_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Listings', listings_path, class: 'nav-link' %>
    </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
      </li>
    <% else %>
      <li class="nav-item">
        <li><%= link_to 'Login', login_path, class: 'nav-link' %></li>
      </li>
      <li class="nav-item">
        <li><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
      </li>
    <% end %>
  </ul>
</nav>

app/views/devices/_device.html.erb
<%= device.name %>
<% unless device_iteration.last? %>
  /&nbsp;
<% end %>

app/views/home/index.html.erb
<div class="col-lg-8">
  <%= button_to 'Connect with SmartThings', {controller: "registration", action: "connect"}, method: :get, class: "Connect with SmartThings" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rabbu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <div class="form-group">
    <h6>Add Devices</h6>
    <%= form.nested_fields_for :devices do |f| %>
      <div class="form-group">
        <%= f.select :name, Device::DEVICE_OPTIONS %>
        <%= f.remove_nested_fields_link %>
      </div>
    <% end %>
    <%= form.add_nested_fields_link :devices %>
  </div>
  <div class="form-group">
    <h6>Reservation</h6>
    <%= form.fields_for :reservation do |f| %>
      <div class="form-group">
        <%= f.label :start_date %>
        <%= f.date_field :start_date %><br>
        <%= f.label :end_date %>
        <%= f.date_field :end_date %>
      </div>
    <% end %>
  </div>
  <div class="form-group form-check form-check-inline">
    <%= form.check_box :automation, :class => "form-check-input" %>
    <%= form.label "Automation", :class => "form-check-label" %>
  </div>

  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/_listing.html.erb
 <tr>
  <th scope="row"><%= listing_counter %></th>
  <td><%= listing.user.email %></td>
  <td><%=  render listing.devices %></td>
  <td><%= listing.reservation.start_date %> / <%= listing.reservation.end_date %></td>
  <td><%= listing.automation %></td>
</tr>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class="display-4">Listings</h1>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">User</th>
      <th scope="col">Devices</th>
      <th scope="col">Reservation</th>
      <th scope="col">Automation</th>
    </tr>
  </thead>
  <tbody>
   <%= render @listings %>
  </tbody>
</table>


<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing for <%= @listing.user.email %></h1>
<h4>Devices</h4>
<% @listing.devices.each do |device| %>
<p><%= device.name %><p>
<% end %>

<h4>Reservation</h4>
<p><%= @listing.reservation.start_date %></p>
<p><%= @listing.reservation.end_date %></p>

<h4>Automation</h4>
<p><%= @listing.automation %></p>
<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>